### ISSUE TITLE
Blog post: How to Call Low-Level z/OS Services from Node.js by Dan Kelosky

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#111]
@mpanch59 and @1000TurquoisePogs please review and let us know if Dan needs to make any changes.

**Comment by Joe-Winchester** [comment]
I just did a review and it looks great !  I've assigned the {Core} tag and added the copyright and trademarks as well as the "more info" final paragraph.  
It should be ready to publish unless the other editors come back with changes or recommendations but I'm happy with it as-is.
