### ISSUE TITLE
Social posts for 5th Birthday of OMP

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/foundation#114]
Suggested by Steven...

> The 5th Birthday of the Open Mainframe Project is on Monday 17th August.  We launched the project at Open Source Summit in Seattle to much fanfare.  The launch of the Project coincided with the launch of IBM's LinuxONE server brand.

**Comment by chrisblumOMP** [comment]
Got it. I will schedule it for Monday. I will reword it a little bit too. Maybe put a cake image. Do we want to write a blog?

**Comment by jmertic** [comment]
@chrisblumOMP - assuming this went out?

Also, I had CS make some graphics we can use...

![OMP_Happy5thBirthday_Social_Twitter copy 5](https://user-images.githubusercontent.com/296737/91175040-281e6500-e6ae-11ea-84f0-944ed1958825.png)
![OMP_Happy5thBirthday_Social_Twitter copy 4](https://user-images.githubusercontent.com/296737/91175044-294f9200-e6ae-11ea-90f0-1fd2c1fc5bbd.png)
![OMP_Happy5thBirthday_Social_Twitter copy 3](https://user-images.githubusercontent.com/296737/91175045-2a80bf00-e6ae-11ea-9dd5-8b9152a38a77.png)

**Comment by chrisblumOMP** [comment]
They went out last Monay.

**Comment by jmertic** [comment]
Great - thanks @chrisblumOMP !
