### ISSUE TITLE
Blog post: Streamline your mainframe development with Zowe Explorer & Zowe CLI (a series): Part 3 — REXX

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#122]
If you’ve read the other articles, then you already have a pretty good idea what this recipe will be about. If not, here is the gist:

Author: Alex Dumitru

@RASakach and @Joe-Winchester would you please review and provide any feedback to Alex?

**Comment by Joe-Winchester** [comment]
I've categorized this as {Core} and added trademarks, updated the display title, and made a few minor grammar corrections.
