### ISSUE TITLE
Add GenevaERS to OMP Dev Analytics

### ISSUE THREAD

**Issue by KipTwitchell** [openmainframeproject/foundation#125]
I didn't see a standard Issue template for this activity.  Let me know what is needed here from the GenevaERS Team.  I'm responding to the [TSC Checklist Item](https://github.com/genevaers/community/tree/master/tsc): "Add project to OMP Dev Analytics ( create issue on foundation repo to trigger )"

**Comment by jmertic** [comment]
No worries - I have requested this now. Generally we will add this in anytime we add/remove a repo or org, mailing list, or slack channel.

**Comment by jmertic** [comment]
Done now @KipTwitchell - it might take a day or so for the stats to fully get updated...

https://lfanalytics.io/projects/open-mainframe-project%2Fgenevaers/dashboard
