### ISSUE TITLE
"I Am A Mainframer" podcast guest - Kip Twitchell

### ISSUE THREAD

**Issue by KipTwitchell** [openmainframeproject/foundation#127]
Please provide details on the guest below.

- Name: Kip Twitchell
- Title: Chair of the GenevaERS OMP Project
- Organization:  IBM
- Background on why they should be interviewed:  This video will give a sense of my content.  https://youtu.be/DKSb-NnJmfs

We will be in touch on scheduling a recording soon!

**Comment by chrisblumOMP** [comment]
Hey Kip - Please send over your email so I can get you scheduled.

**Comment by KipTwitchell** [comment]
Kip.twitchell@us.ibm.com
