### ISSUE TITLE
"I Am A Mainframer" podcast guest - Derek Britton

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/foundation#136]
Please provide details on the guest below.

- Derek Britton
- Global Head of Product Marketing, AMC and IM&G Product Groups
- Micro Focus
- Leader of COBOL Working Group

We will be in touch on scheduling a recording soon!

**Comment by chrisblumOMP** [comment]
@jmertic can you send me his email address so I can get it scheduled?

**Comment by jmertic** [comment]
derek.britton@microfocus.com
