### ISSUE TITLE
Zowe Conformance Web Page Revisions

### ISSUE THREAD

**Issue by RASakach** [openmainframeproject/foundation#14]
We are ready to launch V1 conformance, however, we need to offer users a way to easily see and understand:

-  extenders that are V1 conformant

-   extenders that are 2019 conformant

- extenders that are keeping up with new conformant features being introduced with the current ACTIVE LTS release

The page as is - is very limited and confusing.

Ideally, engage designers to produce a solution

**Comment by RASakach** [comment]
We also need to revise the Broadcom / CA Logo

**Comment by jmertic** [comment]
Thanks @RASakach !

I've attached two screenshots to capture what I'm thinking - basically move the 2019 ones to a new page, and add a few words to the current page indicating the current version. Let me know if this works as a simple fix...


<img width="1534" alt="Screen Shot 2020-05-27 at 11 41 18 AM" src="https://user-images.githubusercontent.com/296737/83046696-5dff6f00-a015-11ea-8bc4-3f62b043ffd6.png">
<img width="1937" alt="Screen Shot 2020-05-27 at 11 43 41 AM" src="https://user-images.githubusercontent.com/296737/83046700-5e980580-a015-11ea-9737-50e2dd4853a8.png">

**Comment by jmertic** [comment]
> We also need to revise the Broadcom / CA Logo

Fixed as a part of https://github.com/openmainframeproject/omp-landscape/pull/18

**Comment by RASakach** [comment]
@jmertic , this looks good.  Thank you!  I would be tempted to add (at the end of the 2019 paragraph) ... "_Offerings listed below satisfied the criteria for the Zowe 2019 conformance program and remain Zowe 2019 Conformant._"  However, if you feel that is overkill, we can leave as is.

**Comment by jmertic** [comment]
I like that suggestion @RASakach  - I'll replace the last sentence with what you provided.

**Comment by jmertic** [comment]
These changes are live now
