### ISSUE TITLE
New Slack Channel - [CHANNEL]

### ISSUE THREAD

**Issue by machikhin** [openmainframeproject/foundation#149]
Please complete all the sections below to request a new channel. Channel requests can take a day or two, so please be patient :-).

# Channel name
tessia

# Channel purpose
support for tessia tool users

# Moderators for the channel
Alexey Machikhin (Alexey.Machikhin@de.ibm.com)
Alexander Efremkin (aefr@de.ibm.com)

# Does this channel have a lifespan? ( if so, please let us know when that is so we can archive it or mark it inactive )
-

**Comment by jmertic** [comment]
Done!
