### ISSUE TITLE
New Mailing List - [PROJECT]

### ISSUE THREAD

**Issue by machikhin** [openmainframeproject/foundation#150]
Please complete all the sections below to request a new mailing list. Requests can take a day or two, so please be patient :-).

# Project name
tessia

# Would you like a combined -user and -dev list, or seperate
Please separate lists.

# Moderators for the mailing list
Alexey Machikhin (Alexey.Machikhin@de.ibm.com)
Alexander Efremkin (Alexander.Efremkin1@de.ibm.com)

**Comment by jmertic** [comment]
These mailing lists are added now and the moderators are set. Let me know of any questions you might have.
