### ISSUE TITLE
Blog Post: Access z/OS Performance and Management Data using CA SYSVIEW and Zowe CLI by Michael Heuzey.

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#151]
@mpanch59 and @Joe-Winchester please review for content.

**Comment by Joe-Winchester** [comment]
Added the {Ecosystem} tag as this article talks about the Zowe Conformant CA Sysview extensions.  Nice to see the Zowe Conformance badge at the end !  Good article and I learnt a lot reading it.
