### ISSUE TITLE
Blog: The ZAAS Client: a library for the API Mediation Layer

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#153]
@joe-winchester and @ykimvicom can you please review

**Comment by Joe-Winchester** [comment]
URL for the blog post https://medium.com/p/822ea2994388.
This looks like a great piece !  The {Core} tagging has been done correctly as well as the trademark.  I updated the subtitle to be a good summary for the front page.
Very happy for this to be published as is.

**Comment by chrisblumOMP** [comment]
Thanks Joe!!

Chris Blum
650.743.6297
