### ISSUE TITLE
OMP Webinar - [TITLE]

### ISSUE THREAD

**Issue by rickperret** [openmainframeproject/foundation#158]
Please refer to the webinar guidelines at https://github.com/openmainframeproject/foundation/blob/master/WEBINAR_GUIDELINES.md before submitting.

- Project Name ( also add in the [TITLE] above ):  Will be something in the OPS are of DevOps
- Webinar submitter:  Rick Perret
- Webinar title:  TBD
- Webinar abstract: 
- Desired Webinar Date:  Meeting with team on 4/7, will confirm date soon after

Speaker(s) Information
- Headshot
- Title
- Company
- Bio
- Email addresses for all speakers/panelists

**Comment by rickperret** [comment]
link is broken to access guidelines

**Comment by jmertic** [comment]
Apologizes @rickperret ! See link below....

https://github.com/openmainframeproject/foundation/blob/master/WEBINAR-GUIDELINES.md
