### ISSUE TITLE
Announce OMP Ambassador program open for applications

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/foundation#159]
The TAC has decided to close the application period for the OMP Ambassador program on 1/13, with the TAC to vote on 1/14. The plan is to appoint up to 10 ambassadors from year 1.

Actions for the group:

- Blog post to announce ( @Maemalynn @chrisblumOMP to draft )
- Include in the newsletter ( @jmertic )
- Social ( @Maemalynn @chrisblumOMP )

**Comment by xrs888** [comment]
Do we have more info on this? I don't see anything on the website. If you have a little more about it, I can put together a blog post.

**Comment by jmertic** [comment]
Yes - details at https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md

**Comment by xrs888** [comment]
Thanks! I will pull something together.

**Comment by xrs888** [comment]
Let me know what you think: https://www.openmainframeproject.org/wp-admin/post.php?post=4270&action=edit

**Comment by jmertic** [comment]
Made a few edits, looks good! @Maemalynn feel free to do a review if you'd like.

**Comment by jmertic** [comment]
Posted at https://www.openmainframeproject.org/blog/2020/12/17/join-the-open-mainframe-project-mentorship-program
