### ISSUE TITLE
Zowe LTS and Zowe V1 Conformance announcement

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/foundation#20]
Announcement plans for Zowe LTS and Zowe Conformant ZOWE V1 announcement.

Tasks to complete

- [X] Finish Zowe Conformant ZOWE V1 program ( done with #9 )
- [X] Socialize new program requirements with Zowe Conformant 2019 offerings
- [X] Process incoming Zowe Conformant ZOWE V1 offerings to include in OMP Landscape ( tracked at https://github.com/openmainframeproject/omp-landscape/pull/18/ )
- [x] Website update ( #14 )  
- [x] Press announcement ( @Maemalynn )

Feel free to add anything I missed!

**Comment by RASakach** [comment]
Please extend Website Update  to include:

- Verbiage that describes prior and current conformance badges
-  Details in issue  https://github.com/openmainframeproject/foundation/issues/14

**Comment by jmertic** [comment]
Thanks @RASakach ! I referenced that other issue which we can work through the details on.
