### ISSUE TITLE
New GitHub repository for Software Discovery Tool deployment

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/foundation#207]
Details, as requested:

- software-discovery-tool-deploy
- @pleia2 @rachejazz @jabostian 
- We want to set up a deployment mechanism for hosting a live version of the Software Discovery Tool, but we don't want to keep our deployment files in the core repository, since others who download and deploy this tool are likely to use their own deployment mechanism, and this won't work for them. This repository will include the deployment files, instructions for how to use GitHub as a deployment mechanism, and make use of GitHub Secrets to store our SSH credentials for the deployment.

**Comment by jmertic** [comment]
done now

**Comment by pleia2** [comment]
We need to be able to use GitHub Secrets for the deployment, but I'm unable to see it under the options. Maybe the standard permissions on new repos are not enough?

"To create secrets for a user account repository, you must be the repository owner. To create secrets for an organization repository, you must have admin access."

https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by rachejazz** [comment]
Anyone updating the secrets, before that, please do let me get ssh access for setting up the sdtuser
Or anyone having the access can go ahead. 
All we need is
hostname, user and pvt key :)

**Comment by jmertic** [comment]
Fixed permissions now :-)
