### ISSUE TITLE
New Mailing List - Linux Distributions Working Group

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/foundation#220]
Please complete all the sections below to request a new mailing list. Requests can take a day or two, so please be patient :-).

# Linux Distributions Working Group

# Combined -user and -dev list

# Moderators for the mailing list: lyz@princessleia.com sarah-julia.kriesch@gmx.de

**Comment by jmertic** [comment]
Looks like you are a moderator now - let me know if there is still an issue.
