### ISSUE TITLE
Blog Post: Zowe Featuring Output Management Solution CA View- The Journey of Discovering Zowe

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#30]
Submitted by: Rodrick Penson at Broadcom

https://medium.com/p/835788892b/edit

@Joe-Winchester and @solsu01
please review and let the author know if you have feedback. Also, mark Core or Ecosystem

**Comment by solsu01** [comment]
@chrisblumOMP I've reviewed and added my comments within the medium draft. Rodrick should see the comments as asterisks next to the line:
![image](https://user-images.githubusercontent.com/35504644/84969552-f2299700-b0e6-11ea-8cd2-c95aff8078b1.png)

Please let Rodrick know that it's ready for him to review/revise.

**Comment by solsu01** [comment]
@chrisblumOMP Rodrick has made the requested changes. I'm good with publishing this.

**Comment by chrisblumOMP** [comment]
Thanks! We will get it out next week!

Chris Blum
650.743.6297
