### ISSUE TITLE
Blog Post: Zowe SDKs and Zowe CLI

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#41]
by Dan Kelosky at Broadcom

@1000TurquoisePogs and @mpanch59 can you please review and mark as core or ecosystem? 

https://medium.com/p/52d496ca77c7/edit?source=email-9c2a7138952e-1592229868974-activity.collection_post_submitted

**Comment by solsu01** [comment]
It looks like https://medium.com/zowe/zowe-sdks-and-zowe-cli-52d496ca77c7 was already published? @chrisblumOMP
