### ISSUE TITLE
Zowe Hackathon Winners Blog

### ISSUE THREAD

**Issue by Maemalynn** [openmainframeproject/foundation#73]
- Draft announcement blog for the hackathon winners and participants

**Comment by jmertic** [comment]
Details from Mae...

> Quick blog post about the Zowe Hackathon winners and them presenting at the Summit
> 
> We can include quotes from the judges for each team (see slide 17 of the below), include PDFs of the presentation, a link to the hackathon webinar and then talk about the the winning team is presenting at the summit and include the link to their talk. 
> 
> Summary of the hackathon (slide 17): https://docs.google.com/presentation/d/1O7T2ZE5skvyBMYr7VGQNXVTG-jfGB-vElXORpoo_PBA/edit#slide=id.g8106153b7c_2_5
> 
> The presentations: https://drive.google.com/drive/folders/1hScXsjou3RCTLsrseD_0Hj5J2e4C0zMj?usp=sharing
> 
> The hackathon webinar where they presented: https://www.youtube.com/watch?v=zIPzaQK2bfU

**Comment by chrisblumOMP** [comment]
It is live and I will promote on Social
