### ISSUE TITLE
Blog Post: Output Management and DevOps - an exercise in automation

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#75]
Published by Stefan Grijinc
Joe and Peter please review this blog post and let me know if it is core or eco.

**Comment by Joe-Winchester** [comment]
I've reviewed the blog post https://medium.com/@stefan.grijincu/output-management-and-devops-an-exercise-in-automation-dacf831ff15 and it looks really good and ready to publish as-is.  

It discusses Broadcom products and Zowe together, so I've given it the {Ecosystem} tag and also added the OMP and Zowe branding links.
