### ISSUE TITLE
Open Mainframe Summit promotion materials

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/foundation#78]
- [x] - Create social materials for community members to share
- [x] - Push on CFP, registration, and sponsorship via social
- [x] - John personally reach out to members and opportunities

**Comment by chrisblumOMP** [comment]
Here are a bunch: 

The inaugural #OMPSummit will bring together mainframers to share best practices, learn technical insight from the best, and network with like-minded individuals who are passionate about the #mainframe industry. Sept. 16-17 - Register: https://bit.ly/3fg77zI


The virtual #OMPSummit will be here before you know it! Collaborate with fellow #mainframers and learn the latest technical insight from the best.  Sept. 16-17 - Register now: https://bit.ly/3fg77zI

Mark your calendars!!  September 16-17 the inaugural #OMPSummit. Register now to learn and network with like-minded individuals who are passionate about the #mainframe industry. Register now: https://bit.ly/3fg77zI

JOIN #OMP for the inaugural #OMPSummit Sept. 16-17.  This is a virtual event to bring together mainframers to share best practices, learn technical insight from the best, and network with like-minded individuals who are passionate about the #mainframe industry. Register: https://bit.ly/3fg77zI

BECOME A SPONSOR at the #OMPSummit – Sept. 16-17 - Learn more by downloading the prospectus: https://bit.ly/2O9ERTx  #mainframe #OMP

Interested in sponsoring at the #OMPSummit this Sept. 16-17? Find out how: https://bit.ly/2O9ERTx #mainframe #OMP

CALL FOR PAPERS – For The Open Mainframe Summit - a virtual event! Submit your talk for any of the three tracks: Executive, Linux on Z and z/OS. Extended until July 17th.  https://bit.ly/3890xbI  #CFP #OMP #OMPSummit

Also went with OMPSummit so we could get more charcters into twitter and it was used in December.

**Comment by chrisblumOMP** [comment]
I update with @OpenMFProject
