### ISSUE TITLE
Blog Post: Streamline your mainframe development with Zowe Explorer & CLI (a series) — Part 1: z/OS Unix…

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#87]
Since Zowe came to light, development on z/OS Unix became much easier for me, in the sense that I can use VS Code and Zowe Explorer…

Author: Alex Dumitru 

@solsu01 and @Joe-Winchester please review and provide any feedback

**Comment by Joe-Winchester** [comment]
This is a great blog by Alex.  It just covers Zowe core content so I've put in the `{Core}` tag and made a few typo corrections.
