### ISSUE TITLE
Open Mainframe Summit schedule announcement

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/foundation#88]
- [x] Speaker acceptance/declines/waitlist sent out ( events staff )
- [x] Build press announcement ( @Maemalynn )
- [x] Prep and schedule social ( @chrisblumOMP )
- [x] Prep and schedule mailing list push ( @jmertic )
- [x] Push out press announcement ( @Maemalynn  )

**Comment by chrisblumOMP** [comment]
Need to add - Add to event page (@chrisblumOMP
