### ISSUE TITLE
New Mailing List - Mainframe Open Education

### ISSUE THREAD

**Issue by gcartier94** [openmainframeproject/foundation#95]
Please complete all the sections below to request a new mailing list. Requests can take a day or two, so please be patient :-).

# Project name

- Mainframe Open Education

# Would you like a combined -user and -dev list, or seperate

- Not necessary at this point

# Moderators for the mailing list

- Guilherme Cartier (gcartier@br.ibm.com)
- Viviane Sanches (vipadua@br.ibm.com)
- Deborah Carbo (deborah.carbo@broadcom.com)
- Lauren Valenti (Lauren.Valenti@Broadcom.com)
- Yvette Lamar (yla@us.ibm.com)

**Comment by jmertic** [comment]
Sorry for the delay @gcartier94 - this is done now. You should have both a -discussion and -private list provisioned. Let me know of any issues or concerns.
